### ISSUE TITLE
Issue with "weighted_accuracy"

### ISSUE THREAD

**Issue by traceprobe** [wentaozhu/protein-cascade-cnn-lstm#2]
I am totally new to keras, and tried to checkout your project and run. But it seems like the conversion in weighted_accuracy is not supported.

Environment: tensorflow-1.0.1 and keras-1.2.2

Error Log:
test@test:~/protein-cascade-cnn-lstm$ python onehotcnn.py 
(array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]), array([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]), (5877, 700, 21), (277, 700, 21), (256, 700, 21), (5877, 700, 8), (277, 700, 8), (256, 700, 8))
Using TensorFlow backend.
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python2.7/dist-packages/keras/layers/core.py:1206: UserWarning: `TimeDistributedDense` is deprecated, And will be removed on May 1st, 2017. Please use a `Dense` layer instead.
  warnings.warn('`TimeDistributedDense` is deprecated, '
Traceback (most recent call last):
  File "onehotcnn.py", line 57, in <module>
    metrics=['weighted_accuracy'])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 716, in compile
    metric_result = metric_fn(y_true, y_pred)
  File "/usr/local/lib/python2.7/dist-packages/keras/metrics.py", line 22, in weighted_accuracy
    K.argmax(y_pred, axis=-1)) * K.sum(y_true, axis=-1)) / K.sum(y_true)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 793, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 575, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype bool for Tensor with dtype float32: 'Tensor("Sum_3:0", shape=(?, ?), dtype=float32)'

**Comment by wentaozhu** [comment]
The weighted_accuracy is implemented by ourselves which is in https://github.com/wentaozhu/protein-cascade-cnn-lstm/blob/master/metrics.py
